<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>StarterKit.Currencies.Api</RootNamespace>
	<AssemblyName>StarterKit.Currencies.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Currency.Tests" />
    <!-- Moq's Castle DynamicProxy needs this to mock internal types. -->
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Lightsoft.AspNetCore.Authorization" />
	<PackageReference Include="Lightsoft.EntityFrameworkCore" />
	<PackageReference Include="Lightsoft.Mediator" />
	<PackageReference Include="Lightsoft.Result" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Currency.Contracts\Currency.Contracts.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Persistence\Persistence.csproj" />
  </ItemGroup>

</Project>
