<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>StarterKit.Modules.Identity</RootNamespace>
	<AssemblyName>StarterKit.Modules.Identity</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Identity.Tests" />
    <InternalsVisibleTo Include="StarterKit.Modules.Identity.Web" />
    <InternalsVisibleTo Include="MSSQL" />
    <InternalsVisibleTo Include="PostgreSQL" />
    <InternalsVisibleTo Include="Sqlite" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Lightsoft.ActiveDirectory" />
    <PackageReference Include="Lightsoft.Caching" />
    <PackageReference Include="Lightsoft.SharedKernel" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Identity.Contracts\Identity.Contracts.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Persistence\Persistence.csproj" />
  </ItemGroup>

</Project>
