<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>StarterKit.Orders.Contracts</RootNamespace>
	<AssemblyName>StarterKit.Orders.Contracts</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Lightsoft.AspNetCore.Authorization" />
	<PackageReference Include="Lightsoft.Mediator" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Catalog.Contracts\Catalog.Contracts.csproj" />
    <ProjectReference Include="..\Location.Contracts\Location.Contracts.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
