<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>17813bc1-5906-466a-bd4b-1e3d982b21df</UserSecretsId>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.5.4" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StarterKit.WebApi\StarterKit.WebApi.csproj" />
  </ItemGroup>

</Project>
