// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarterKit.Inventory.Api.Data;

#nullable disable

namespace Sqlite.Inventory
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("StarterKit.Inventory.Api.Domain.StockAdjustments.StockAdjustment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PerformedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReversesAdjustmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SourceLineId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitCostBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValueDeltaBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ReversesAdjustmentId");

                    b.HasIndex("ProductId", "LocationId");

                    b.HasIndex("SourceType", "SourceId");

                    b.ToTable("StockAdjustments", "inventory");
                });

            modelBuilder.Entity("StarterKit.Inventory.Api.Domain.StockLevels.StockLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalValueBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "LocationId")
                        .IsUnique();

                    b.ToTable("StockLevels", "inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
