<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\ModuleTests.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\src\Approval.Contracts\Approval.Contracts.csproj" />
    <ProjectReference Include="..\..\src\LeaveManagement.Api\LeaveManagement.Api.csproj" />
    <ProjectReference Include="..\..\src\LeaveManagement.Contracts\LeaveManagement.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Organization.Contracts\Organization.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
