// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarterKit.Transfers.Api.Data;

#nullable disable

namespace Sqlite.Transfers
{
    [DbContext(typeof(TransfersDbContext))]
    partial class TransfersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("transfers")
                .HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("StarterKit.Transfers.Api.Domain.StockTransfers.StockTransfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CancelledAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancelledReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClosedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClosedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationLocationId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationLocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DispatchedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PostingStartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReceivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RequestedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceLocationId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransferCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("PostingStartedAt")
                        .HasFilter("[PostingStartedAt] IS NOT NULL");

                    b.HasIndex("SourceLocationId");

                    b.HasIndex("TransferCode")
                        .IsUnique();

                    b.HasIndex("Status", "Created");

                    b.ToTable("StockTransfers", "transfers");
                });

            modelBuilder.Entity("StarterKit.Transfers.Api.Domain.StockTransfers.TransferLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("QtyClosedShort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtyDispatched")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtyReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("TransferId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitCostBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransferId");

                    b.ToTable("TransferLines", "transfers");
                });

            modelBuilder.Entity("StarterKit.Transfers.Api.Domain.StockTransfers.TransferReceipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientRequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TransferId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("VoidedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Created");

                    b.HasIndex("TransferId", "ClientRequestId")
                        .IsUnique();

                    b.ToTable("TransferReceipts", "transfers");
                });

            modelBuilder.Entity("StarterKit.Transfers.Api.Domain.StockTransfers.TransferReceiptLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastModified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReceiptId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TransferLineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("TransferReceiptLines", "transfers");
                });

            modelBuilder.Entity("StarterKit.Transfers.Api.Domain.StockTransfers.TransferLine", b =>
                {
                    b.HasOne("StarterKit.Transfers.Api.Domain.StockTransfers.StockTransfer", "Transfer")
                        .WithMany("Lines")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("StarterKit.Transfers.Api.Domain.StockTransfers.TransferReceipt", b =>
                {
                    b.HasOne("StarterKit.Transfers.Api.Domain.StockTransfers.StockTransfer", "Transfer")
                        .WithMany("Receipts")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("StarterKit.Transfers.Api.Domain.StockTransfers.TransferReceiptLine", b =>
                {
                    b.HasOne("StarterKit.Transfers.Api.Domain.StockTransfers.TransferReceipt", "Receipt")
                        .WithMany("Lines")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("StarterKit.Transfers.Api.Domain.StockTransfers.StockTransfer", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("StarterKit.Transfers.Api.Domain.StockTransfers.TransferReceipt", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
