allowBuilds:
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - react-dom@19.3.0
  - react@19.3.0
  - scheduler@0.28.0
  - '@types/react-dom@19.3.0'
  - '@types/react@19.3.0'
  - '@types/node@26.5.1'
overrides:
  fast-uri: ^3.1.5
  js-yaml: ^4.3.1
  hono: ^4.12.34
  minimatch@3.1.5>brace-expansion: ^1.1.18
  minimatch@10.2.6>brace-expansion: ^5.0.9
  '@types/react': 19.3.0
  '@types/react-dom': 19.3.0
