"use server";

import { revalidatePath } from "next/cache";
import { resolveSession } from "@/modules/identity/user-profile";
import { receiveStockTransfer } from "@/modules/transfers/api/transfers.api";
import { MAX_RECEIPT_LINES, MAX_TRANSFER_LINE_QUANTITY } from "@/modules/transfers/types/transfer";
import { isNumericId } from "@/modules/transfers/utils/params";

export interface ReceiveTransferActionState {
  error?: string;
  success?: boolean;
  receiptId?: string;
  /**
   * True when the backend deterministically refused the request (400/403/404/409): nothing was
   * recorded under this request id and it must not be reused (e.g. a Voided receipt keeps its id
   * forever). False for ambiguous failures (network error, timeout, 5xx), where the same id must
   * be retried so the resubmit stays idempotent.
   */
  definitive?: boolean;
}

const DEFINITIVE_CODES = new Set(["bad_request", "conflict", "not_found", "forbidden"]);

export interface ReceiveTransferLineInput {
  transferLineId: string;
  quantity: number;
}

/**
 * Records a receipt. `clientRequestId` is generated by the client per opened dialog and reused
 * across retries so a resubmitted receipt is a backend no-op instead of a double receipt.
 */
export async function receiveTransferAction(
  transferId: string,
  clientRequestId: string,
  lines: ReceiveTransferLineInput[],
): Promise<ReceiveTransferActionState> {
  const session = await resolveSession();
  if (!session) {
    return { error: "Your session has expired. Please sign in again." };
  }

  if (!isNumericId(transferId)) {
    return { error: "Invalid transfer." };
  }

  const requestId = clientRequestId.trim();
  if (!requestId || requestId.length > 100) {
    return { error: "Invalid request. Close the dialog and try again." };
  }

  if (lines.length === 0) {
    return { error: "Enter a quantity for at least one line." };
  }

  if (lines.length > MAX_RECEIPT_LINES) {
    return { error: `A receipt can have at most ${MAX_RECEIPT_LINES} lines.` };
  }

  if (new Set(lines.map((line) => line.transferLineId)).size !== lines.length) {
    return { error: "A transfer line can appear only once per receipt." };
  }

  for (const line of lines) {
    if (!isNumericId(line.transferLineId)) {
      return { error: "Invalid transfer line." };
    }
    if (!Number.isInteger(line.quantity) || line.quantity < 1 || line.quantity > MAX_TRANSFER_LINE_QUANTITY) {
      return { error: "Quantities must be whole numbers between 1 and 1,000,000." };
    }
  }

  const result = await receiveStockTransfer(transferId, { clientRequestId: requestId, lines });

  if (!result.isSuccess) {
    return {
      error: result.message || "Failed to record receipt.",
      definitive: DEFINITIVE_CODES.has(result.code),
    };
  }

  revalidatePath("/transfers");
  revalidatePath(`/transfers/${transferId}`);
  return { success: true, receiptId: result.data ? String(result.data) : undefined };
}
