<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\ModuleTests.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\src\Identity\Identity.csproj" />
    <ProjectReference Include="..\..\src\Identity.Web\Identity.Web.csproj" />
    <ProjectReference Include="..\..\src\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
