<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\ModuleTests.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\src\Identity.Contracts\Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Organization.Api\Organization.Api.csproj" />
    <ProjectReference Include="..\..\src\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
