<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>StarterKit.Purchasing.Contracts</RootNamespace>
	<AssemblyName>StarterKit.Purchasing.Contracts</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Lightsoft.AspNetCore.Authorization" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
